
;
/**
  *  * app.js — chat application logic, multi-contact version.
  *   *
  *    * IMPORTANT FIX vs earlier version: previously, sending used one
  *     * in-memory ratchet ("activeRatchet") while receiving loaded a FRESH
    *      * copy from storage each time. If a send and a receive happened close
  *       * together, both would read storage before either had saved, and
  *        * whichever saved last would silently erase the other's progress —
  *         * corrupting the conversation until you reloaded the page.
  *          *
  *           * Fix: there is now exactly ONE in-memory ratchet object per contact
    *            * (ratchetCache), and every operation that touches it — sending OR
  *             * receiving — goes through a single queue that runs one at a time.
  *              * No more race, no more "have to refresh to see it."
  *               */

let myIdentity;
let myFingerprint;
let ws;
let activeFingerprint = null; // which contact's conversation is open

const el = (id) => document.getElementById(id);

// ---- Single source of truth for ratchet state, one per contact ----
//
// const ratchetCache = new Map(); // fingerprint -> RatchetBrowser instance
//
// function getRatchet(fingerprint) {
//   if (ratchetCache.has(fingerprint)) return ratchetCache.get(fingerprint);
//
//     const contact = SecnetContacts.getContact(fingerprint);
//       if (!contact || !contact.ratchetState) return null;
//
//         const ratchet = SecnetRatchet.RatchetBrowser.fromJSON(contact.ratchetState);
//           ratchetCache.set(fingerprint, ratchet);
//             return ratchet;
//             }
//
//             function persistRatchet(fingerprint) {
//               const ratchet = ratchetCache.get(fingerprint);
//                 if (!ratchet) return;
//                   SecnetContacts.updateRatchetState(fingerprint, ratchet.toJSON());
//                   }
//
//                   // ALL encrypt/decrypt operations, whether sending or receiving, go
//                   // through this single queue so two operations never run concurrently
//                   // against the same in-memory state.
//                   let opQueue = Promise.resolve();
//                   function enqueue(fn) {
//                     const result = opQueue.then(fn, fn);
//                       opQueue = result.catch(() => {}); // one failure shouldn't jam the queue forever
//                         return result;
//                         }
//
//                         function packetToJSON(packet) {
//                           return {
//                               index: packet.index,
//                                   nonce: SecnetIdentity.toB64(packet.nonce),
//                                       ciphertext: SecnetIdentity.toB64(packet.ciphertext),
//                                         };
//                                         }
//                                         function packetFromJSON(obj) {
//                                           return {
//                                               index: obj.index,
//                                                   nonce: SecnetIdentity.fromB64(obj.nonce),
//                                                       ciphertext: SecnetIdentity.fromB64(obj.ciphertext),
//                                                         };
//                                                         }
//
//                                                         // ---- Rendering ----
//
//                                                         function renderContactList() {
//                                                           const list = el('contactList');
//                                                             list.innerHTML = '';
//                                                               const contacts = SecnetContacts.listContacts();
//
//                                                                 for (const c of contacts) {
//                                                                     const item = document.createElement('div');
//                                                                         item.className = 'contact-item' + (c.fingerprint === activeFingerprint ? ' active' : '');
//                                                                             item.textContent = c.name;
//                                                                                 item.addEventListener('click', () => openContact(c.fingerprint));
//                                                                                     list.appendChild(item);
//                                                                                       }
//                                                                                       }
//
//                                                                                       function renderChatLog(messages) {
//                                                                                         const chatLog = el('chatLog');
//                                                                                           chatLog.innerHTML = '';
//                                                                                             for (const m of messages) renderOneMessage(m);
//                                                                                               chatLog.scrollTop = chatLog.scrollHeight;
//                                                                                               }
//
//                                                                                               function renderOneMessage(m) {
//                                                                                                 const chatLog = el('chatLog');
//                                                                                                   const wrapper = document.createElement('div');
//                                                                                                     wrapper.className = `msg ${m.who}`;
//
//                                                                                                       if (m.kind === 'text') {
//                                                                                                           wrapper.textContent = `${m.who === 'me' ? 'You' : 'Friend'}: ${m.content}`;
//                                                                                                             } else if (m.kind === 'image') {
//                                                                                                                 const label = document.createElement('div');
//                                                                                                                     label.textContent = m.who === 'me' ? 'You sent an image:' : 'Friend sent an image:';
//                                                                                                                         const img = document.createElement('img');
//                                                                                                                             img.src = m.content;
//                                                                                                                                 img.style.maxWidth = '240px';
//                                                                                                                                     img.style.display = 'block';
//                                                                                                                                         wrapper.appendChild(label);
//                                                                                                                                             wrapper.appendChild(img);
//                                                                                                                                               } else if (m.kind === 'voice') {
//                                                                                                                                                   const label = document.createElement('div');
//                                                                                                                                                       label.textContent = m.who === 'me' ? 'You sent a voice note:' : 'Friend sent a voice note:';
//                                                                                                                                                           const audio = document.createElement('audio');
//                                                                                                                                                               audio.controls = true;
//                                                                                                                                                                   audio.src = m.content;
//                                                                                                                                                                       wrapper.appendChild(label);
//                                                                                                                                                                           wrapper.appendChild(audio);
//                                                                                                                                                                             }
//
//                                                                                                                                                                               chatLog.appendChild(wrapper);
//                                                                                                                                                                               }
//
//                                                                                                                                                                               function addAndRenderMessage(fingerprint, message) {
//                                                                                                                                                                                 SecnetContacts.appendMessageToHistory(fingerprint, message);
//                                                                                                                                                                                   if (fingerprint === activeFingerprint) {
//                                                                                                                                                                                       renderOneMessage(message);
//                                                                                                                                                                                           el('chatLog').scrollTop = el('chatLog').scrollHeight;
//                                                                                                                                                                                             }
//                                                                                                                                                                                             }
//
//                                                                                                                                                                                             // ---- Conversation management ----
//
//                                                                                                                                                                                             function openContact(fingerprint) {
//                                                                                                                                                                                               activeFingerprint = fingerprint;
//                                                                                                                                                                                                 const contact = SecnetContacts.getContact(fingerprint);
//                                                                                                                                                                                                   if (!contact) return;
//
//                                                                                                                                                                                                     el('activeContactName').textContent = contact.name;
//                                                                                                                                                                                                       el('activeContactFingerprint').textContent = fingerprint;
//                                                                                                                                                                                                         el('chatPanel').style.display = 'block';
//
//                                                                                                                                                                                                           renderChatLog(contact.messages);
//                                                                                                                                                                                                             renderContactList();
//                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                             async function addContactFlow() {
//                                                                                                                                                                                                               const name = el('newContactName').value.trim();
//                                                                                                                                                                                                                 const keyB64 = el('newContactKey').value.trim();
//                                                                                                                                                                                                                   if (!name || !keyB64) return;
//
//                                                                                                                                                                                                                     const publicKeyBytes = SecnetIdentity.fromB64(keyB64);
//                                                                                                                                                                                                                       const fingerprint = SecnetIdentity.fingerprint(publicKeyBytes);
//
//                                                                                                                                                                                                                         SecnetContacts.addContact(fingerprint, name, keyB64);
//
//                                                                                                                                                                                                                           const sharedSecret = await SecnetIdentity.deriveSharedSecret(myIdentity.secretKey, publicKeyBytes);
//                                                                                                                                                                                                                             const ratchet = new SecnetRatchet.RatchetBrowser(sharedSecret);
//                                                                                                                                                                                                                               ratchetCache.set(fingerprint, ratchet);
//                                                                                                                                                                                                                                 persistRatchet(fingerprint);
//
//                                                                                                                                                                                                                                   el('newContactName').value = '';
//                                                                                                                                                                                                                                     el('newContactKey').value = '';
//                                                                                                                                                                                                                                       renderContactList();
//                                                                                                                                                                                                                                         openContact(fingerprint);
//                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                         // ---- Networking ----
//
//                                                                                                                                                                                                                                         let reconnectAttempts = 0;
//                                                                                                                                                                                                                                         let heartbeatInterval = null;
//
//                                                                                                                                                                                                                                         function connectWebSocket() {
//                                                                                                                                                                                                                                           const protocol = location.protocol === 'https:' ? 'wss' : 'ws';
//                                                                                                                                                                                                                                             ws = new WebSocket(`${protocol}://${location.host}`);
//
//                                                                                                                                                                                                                                               ws.onopen = () => {
//                                                                                                                                                                                                                                                   reconnectAttempts = 0;
//                                                                                                                                                                                                                                                       ws.send(JSON.stringify({ type: 'register', fingerprint: myFingerprint }));
//                                                                                                                                                                                                                                                           el('status').textContent = 'Connected to relay';
//
//                                                                                                                                                                                                                                                               clearInterval(heartbeatInterval);
//                                                                                                                                                                                                                                                                   heartbeatInterval = setInterval(() => {
//                                                                                                                                                                                                                                                                         if (ws.readyState === WebSocket.OPEN) {
//                                                                                                                                                                                                                                                                                 ws.send(JSON.stringify({ type: 'ping' }));
//                                                                                                                                                                                                                                                                                       }
//                                                                                                                                                                                                                                                                                           }, 20000);
//                                                                                                                                                                                                                                                                                             };
//
//                                                                                                                                                                                                                                                                                               ws.onclose = () => {
//                                                                                                                                                                                                                                                                                                   clearInterval(heartbeatInterval);
//                                                                                                                                                                                                                                                                                                       el('status').textContent = 'Disconnected — reconnecting...';
//                                                                                                                                                                                                                                                                                                           reconnectAttempts++;
//                                                                                                                                                                                                                                                                                                               const delay = Math.min(1000 * reconnectAttempts, 8000);
//                                                                                                                                                                                                                                                                                                                   setTimeout(connectWebSocket, delay);
//                                                                                                                                                                                                                                                                                                                     };
//
//                                                                                                                                                                                                                                                                                                                       ws.onerror = () => {
//                                                                                                                                                                                                                                                                                                                           ws.close();
//                                                                                                                                                                                                                                                                                                                             };
//
//                                                                                                                                                                                                                                                                                                                               ws.onmessage = (event) => {
//                                                                                                                                                                                                                                                                                                                                   enqueue(() => handleIncoming(event)).catch((err) => {
//                                                                                                                                                                                                                                                                                                                                         console.error('Failed to process incoming message:', err);
//                                                                                                                                                                                                                                                                                                                                             });
//                                                                                                                                                                                                                                                                                                                                               };
//                                                                                                                                                                                                                                                                                                                                               }
//
//                                                                                                                                                                                                                                                                                                                                               async function handleIncoming(event) {
//                                                                                                                                                                                                                                                                                                                                                 const msg = JSON.parse(event.data);
//                                                                                                                                                                                                                                                                                                                                                   if (msg.type !== 'relay') return;
//
//                                                                                                                                                                                                                                                                                                                                                     const fromFingerprint = msg.from;
//                                                                                                                                                                                                                                                                                                                                                       const contact = SecnetContacts.getContact(fromFingerprint);
//                                                                                                                                                                                                                                                                                                                                                         if (!contact) return; // message from someone not in your contacts — ignored
//
//                                                                                                                                                                                                                                                                                                                                                           const ratchet = getRatchet(fromFingerprint);
//                                                                                                                                                                                                                                                                                                                                                             if (!ratchet) return;
//
//                                                                                                                                                                                                                                                                                                                                                               const payload = msg.packet;
//
//                                                                                                                                                                                                                                                                                                                                                                 if (payload.kind === 'text') {
//                                                                                                                                                                                                                                                                                                                                                                     const packet = packetFromJSON(payload.packet);
//                                                                                                                                                                                                                                                                                                                                                                         const plaintext = await ratchet.decrypt(packet);
//                                                                                                                                                                                                                                                                                                                                                                             persistRatchet(fromFingerprint);
//                                                                                                                                                                                                                                                                                                                                                                                 addAndRenderMessage(fromFingerprint, {
//                                                                                                                                                                                                                                                                                                                                                                                       who: 'friend', kind: 'text', content: new TextDecoder().decode(plaintext), ts: Date.now(),
//                                                                                                                                                                                                                                                                                                                                                                                           });
//                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                               if (payload.kind === 'media') {
//                                                                                                                                                                                                                                                                                                                                                                                                   const envelope = {
//                                                                                                                                                                                                                                                                                                                                                                                                         mediaId: payload.mediaId,
//                                                                                                                                                                                                                                                                                                                                                                                                               mediaType: payload.mediaType,
//                                                                                                                                                                                                                                                                                                                                                                                                                     totalChunks: payload.chunks.length,
//                                                                                                                                                                                                                                                                                                                                                                                                                           chunks: payload.chunks.map(packetFromJSON),
//                                                                                                                                                                                                                                                                                                                                                                                                                               };
//                                                                                                                                                                                                                                                                                                                                                                                                                                   const fileBytes = await SecnetMedia.reassembleMedia(envelope, ratchet);
//                                                                                                                                                                                                                                                                                                                                                                                                                                       persistRatchet(fromFingerprint);
//                                                                                                                                                                                                                                                                                                                                                                                                                                           const blob = new Blob([fileBytes], { type: payload.mediaType === 'image' ? 'image/png' : 'audio/webm' });
//                                                                                                                                                                                                                                                                                                                                                                                                                                               const url = URL.createObjectURL(blob);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                   addAndRenderMessage(fromFingerprint, { who: 'friend', kind: payload.mediaType, content: url, ts: Date.now() });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                     async function init() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                       myIdentity = SecnetIdentity.loadOrCreateIdentity();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                         myFingerprint = SecnetIdentity.fingerprint(myIdentity.publicKey);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                           el('myFingerprint').textContent = myFingerprint;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                             el('myPublicKey').textContent = SecnetIdentity.toB64(myIdentity.publicKey);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                               renderContactList();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                 connectWebSocket();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                 async function sendText() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const text = el('messageInput').value;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!text || !activeFingerprint) return;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const fingerprint = activeFingerprint;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                         el('messageInput').value = '';
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await enqueue(async () => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const ratchet = getRatchet(fingerprint);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!ratchet) return;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const packet = await ratchet.encrypt(new TextEncoder().encode(text));
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           persistRatchet(fingerprint);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ws.send(JSON.stringify({
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type: 'relay',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           to: fingerprint,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 packet: { kind: 'text', packet: packetToJSON(packet) },
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }));
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         addAndRenderMessage(fingerprint, { who: 'me', kind: 'text', content: text, ts: Date.now() });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           async function sendFile(file, mediaType) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!activeFingerprint) return;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const fingerprint = activeFingerprint;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const bytes = new Uint8Array(await file.arrayBuffer());
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await enqueue(async () => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const ratchet = getRatchet(fingerprint);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!ratchet) return;
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const envelope = await SecnetMedia.prepareMedia(bytes, mediaType, ratchet);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   persistRatchet(fingerprint);
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ws.send(JSON.stringify({
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type: 'relay',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   to: fingerprint,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         packet: {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 kind: 'media',
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         mediaId: envelope.mediaId,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 mediaType: envelope.mediaType,
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         chunks: envelope.chunks.map(packetToJSON),
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               },
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }));
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const url = URL.createObjectURL(file);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           addAndRenderMessage(fingerprint, { who: 'me', kind: mediaType, content: url, ts: Date.now() });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // ---- Voice recording ----
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let mediaRecorder = null;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let recordedChunks = [];
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             async function startRecording() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 mediaRecorder = new MediaRecorder(stream);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   recordedChunks = [];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     mediaRecorder.ondataavailable = (e) => recordedChunks.push(e.data);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       mediaRecorder.onstop = async () => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const blob = new Blob(recordedChunks, { type: 'audio/webm' });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const file = new File([blob], 'voice-note.webm', { type: 'audio/webm' });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   await sendFile(file, 'voice');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     };
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       mediaRecorder.start();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         el('recordBtn').textContent = 'Stop recording';
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         function stopRecording() {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (mediaRecorder) mediaRecorder.stop();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             el('recordBtn').textContent = 'Record voice note';
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             window.addEventListener('DOMContentLoaded', () => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               init();
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 el('addContactBtn').addEventListener('click', addContactFlow);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   el('sendBtn').addEventListener('click', sendText);
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     el('messageInput').addEventListener('keydown', (e) => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (e.key === 'Enter') sendText();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             el('imageInput').addEventListener('change', (e) => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const file = e.target.files[0];
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (file) sendFile(file, 'image');
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         e.target.value = '';
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });
//
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let recording = false;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               el('recordBtn').addEventListener('click', () => {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   recording = !recording;
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (recording) startRecording();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           else stopRecording();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             i
